#!/bin/bash -e

#DEBHELPER#

if [ "${1}" = "configure" ] && [ "$2" != "" ] ; then
    if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
	if test -x /var/lib/dpkg/info/libgnome2-common.postinst; then
	    /var/lib/dpkg/info/libgnome2-common.postinst configure
	fi
    fi
fi
