#!/bin/sh -e

#DEBHELPER#

if [ "${1}" = "upgrade" ]; then
    if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
	update-alternatives --remove gnome-splash \
	    /usr/share/images/desktop-base/Splash-Debian.png
	update-alternatives --remove gnome-splash \
	    /usr/share/images/desktop-base/Splash-EvolvingTux.png
	update-alternatives --remove gnome-splash \
	    /usr/share/images/desktop-base/Splash-Debian_red.png

	dpkg-divert --package desktop-base --rename \
	    --divert /usr/share/pixmaps/splash/gnome-splash.png.orig \
	    --remove /usr/share/pixmaps/splash/gnome-splash.png
    fi
fi