#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    # remove background alternatives
    update-alternatives --remove desktop-background \
	/usr/share/images/desktop-base/debblue-1600x1200.png

    update-alternatives --remove desktop-background \
	/usr/share/images/desktop-base/debian-background.svg

    update-alternatives --remove desktop-background \
	/usr/share/images/desktop-base/bluedeb-1024x768.jpg

    update-alternatives --remove desktop-background \
	/usr/share/images/desktop-base/Debian.jpg

    # remove splash alternatives
    update-alternatives --remove desktop-splash \
	/usr/share/images/desktop-base/Splash-debblue.png

    update-alternatives --remove desktop-splash \
	/usr/share/images/desktop-base/Splash-Debian.png

    update-alternatives --remove desktop-splash \
	/usr/share/images/desktop-base/Splash-Debian_red.png
fi